### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [barafael/raPID#4]
In the file raPID/src/imu.cpp you can remove this line: `while (Wire.available() < 6) {}`. It is used twice.

The Wire.requestFrom() waits until the complete I2C transaction on the bus has finished. There is no need to wait for something after the call to Wire.requestFrom().
In case of a bus collision or an error that the Wire library could detect (it can not detect most problems), then the Wire.available() will probably return zero, and that loop will halt the sketch.

**Comment by barafael** [comment]
Thanks for spotting that! I will remove the line. Awesome!

**Comment by Koepel** [comment]
Thanks. That was fast.

You use the I2Cdev code, which is using the Wire library in a wrong way ( https://github.com/jrowberg/i2cdevlib/issues/265 ). That library is no longer maintained and the issues are piling up. The library is also a little outdated. Your copy of "init_mpu6050" is therefor also a little outdated. The FastWire option is not really needed and setting the TWBR for the speed is no longer needed, since there is a Wire.setClock() function now.

Changing the I2Cdev.cpp is risky. There is not much you or me can do about the library at Github. Keep in mind that the library is slower than needed, with extra unnecessary bus activity that slows it down. With the current version of the AVR Wire library the I2Cdev library works (despite the wrong use), so for now it is okay.

**Comment by barafael** [comment]
I guess it would be possible to use the i2c_t3 library in I2Cdev, however as you said it could be a lot of work.

I have sufficient power on my microcontroller to be able to do my own sensor fusion, so [this library by Kris Winer](https://github.com/kriswiner/MPU6050) is worth looking at for me.
In the long run, I want to use a different sensor anyway, as InvenSense has presented really good new options as recent as CES.

Thank you for pointing out the issues!

**Comment by Koepel** [comment]
You might consider to upgrade to the MPU-9250 and try the Kris Winer AHRS fusion. Sometimes a MPU-6050 module is shipped with a smaller capacitor which causes extra noise. The MPU-9250 doesn't have that capacitor.

**Comment by barafael** [comment]
Ok, that sounds like it will improve the IMU quite a bit. I am wondering about the tradeoffs of using on-chip sensor fusion vs. doing it on the main board. I guess I will try both!

BTW, great job on helping all those other people use the Wire library correctly.
